### PR TITLE
fix: improve the early adopters plan input section

### LINKED ISSUE #597: [improvement]: improve the early adopters plan input section
## Improvement Description

1. The step message is out of sync with the flow. Steps can be reduced by using the "Next" button on the email input field without having to click the "Next" button on the name input field.

2. The "Sign" button becomes clickable after making changes in the name input field. The "Sign" button should only become enabled after clicking the "Next" button in the name input field for the first time.

3.  After completing all the steps, when the "Sign" button becomes clickable, the message currently displayed states "1 step(s) until signed." This can be quite confusing because all the steps have already been completed, and it's ready to be signed. This message should be replaced with a success message. 

loom video:- https://www.loom.com/share/a2d5bfa634534d2ebf65bb858242765b
## Proposed Solution

1. The "Sign" button is only enabled for clicking after clicking the "Next" button in the name input field.
2. After completing all the steps, the step message should be a success message.

## Additional Context

I'm seeking community feedback and suggestions to improve this.

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #597 

Screenshot 2023-10-30 193046

### CODE REVIEW

File: apps/marketing/src/components/(marketing)/widget.tsx [hunk 1]
```diff
@@ -226,7 +226,9 @@ export const Widget = ({ className, children, ...props }: WidgetProps) => {
                           type="button"
                           className="bg-primary h-full w-14 rounded"
                           disabled={!field.value || !!errors.email?.message}
-                          onClick={() => onNextStepClick()}
+                          onClick={() => {
+                            if (step === 'EMAIL') onNextStepClick();
```
Comment (Mythie) [inline apps/marketing/src/components/(marketing)/widget.tsx:230]: No single line if statements please, you can do `step === 'EMAIL' && onNextStepClick();` if you want to be concise.

Comment (anikdhabal) [reply apps/marketing/src/components/(marketing)/widget.tsx]: Thanks for the Review. Done

**Review by Mythie — APPROVED** [review]

**Comment by Mythie** [comment]
Thanks for your contribution 🤗

captain-america-salute
