### PR TITLE
fix: Remove document on go back click on step 1

### LINKED ISSUE #903: Unable to re-attach document in singleplayer mode
### Issue Description

I recently wanted to get my rent receipts signed by the landlord, so I headed over to single-player mode to start the signing process. I accidentally uploaded the wrong file and realized it after some time. I wanted to re-upload the correct document but there wasn't an easy way to do it. I had to navigate back and forth to start the process afresh, which is not very intuitive. 

### Steps to Reproduce

1. Navigate to single-player mode (https://documenso.com/singleplayer)
2. Upload any document
3. Try removing and reuploading a new document without clicking on the back/forth button on the browser navbar. 

### Expected Behavior

We should be able to re-upload the document once any document is uploaded. The "Go back" button can be rendered as "Reupload" or something similar once the document is uploaded. Currently, it is unresponsive on step 1.
In addition, the progress bar is 50% complete simply by navigating to single-player mode and without having to upload any document. I feel the progress bar should update to 50% or any number after the user adds a document. I might be wrong here, but I'm just thinking out loud.

### Current Behavior

Currently, there is no simple way to remove and add a new document, and the "Go back" button is unresponsive in Step 1.

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

Version 121.0.6167.140 (Official Build) (64-bit)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by prajwalkulkarni**
# :dizzy: Changelog
:star: Fixes #903 
:star: Invoke `onBackStep` on "Go Back" click and conditionally render Go back label string.

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by prajwalkulkarni** [comment]
Done!

File: packages/ui/primitives/document-flow/add-fields.tsx [hunk 1]
```diff
@@ -566,7 +566,9 @@ export const AddFieldsFormPartial = ({
           onGoBackClick={() => {
             previousStep();
             remove();
+            documentFlow.onBackStep?.();
           }}
+          goBackLabel={currentStep === 1 && typeof documentFlow.onBackStep === "function" ? "Remove" : undefined}
```
[the remark this answers is not in the document]
Comment (prajwalkulkarni) [reply packages/ui/primitives/document-flow/add-fields.tsx]: Done. Seems like I had disabled "Format on Save" on my VSCode. I've pushed the changes. Kindly review.

File: packages/ui/primitives/document-flow/add-fields.tsx [hunk 2]
```diff
@@ -566,7 +566,13 @@ export const AddFieldsFormPartial = ({
           onGoBackClick={() => {
             previousStep();
             remove();
+            documentFlow.onBackStep?.();
           }}
+          goBackLabel={
+            currentStep === 1 && typeof documentFlow.onBackStep === 'function'
+              ? 'Remove'
+              : undefined
+          }
```
Comment (Mythie) [inline packages/ui/primitives/document-flow/add-fields.tsx:575]: This wouldn't work since it would also affect the main webapp where the document wouldn't be removed 🤔

Comment (prajwalkulkarni) [reply packages/ui/primitives/document-flow/add-fields.tsx]: I did a global lookup of where all `AddFieldsFormPartial` is used and it looks like it is used only in singleplayermode and `edit-document.tsx` which is a part of main webapp dashboard. The property `documentFlow.fields` in `edit-document.tsx` doesn't have the `onBackStep` property implemented, meaning `typeof documentFlow.onBackStep` would be falsy, thereby the default fallback string would be rendered (Please correct me If I'm wrong here). Nonetheless, I've made the changes by adding an additional optional prop to the `AddFieldsFormPartial` component to keep it future-proof. Kindly check.

**Comment by Mythie** [comment]
Lgtm 💚
