### PR TITLE
fix: improve the validation message for documenso app

### LINKED ISSUE #635: improvement: fix the validation message for documenso app
### Issue Description

There are some input fields where I believe improvements are needed for the error messages displayed when an input field is empty, and someone attempts to proceed to the next step.

1.) In the Sign-In form and the reset password form, when the password field is empty, it shows the message "String must contain at least 6 character(s)."

2.) The email field in the "Add Signer" form displays "String must contain at least 1 character(s)."

### Steps to Reproduce

_No response_

### Expected Behavior

1.)  When the password field is empty, the error message should be "Invalid Password," similar to the email field.

2.) Instead of "String must contain at least 1 character(s)," the email field should display "Email is required," similar to how the name field behaves.

### Current Behavior

_No response_

### Screenshots (optional)

Current behavior:-

Screenshot 2023-11-08 131922

Screenshot 2023-11-08 132454

Screenshot 2023-11-08 145659

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

_No response_

### Version [e.g., 2.0.1]

_No response_

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #635 

Screenshot 2023-11-08 195029
Screenshot 2023-11-08 192253
Screenshot 2023-11-08 191351

### CODE REVIEW

File: apps/web/src/components/forms/signup.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ import { useToast } from '@documenso/ui/primitives/use-toast';
 export const ZSignUpFormSchema = z.object({
   name: z.string().trim().min(1, { message: 'Please enter a valid name.' }),
   email: z.string().email().min(1),
-  password: z.string().min(6).max(72),
+  password: z.string().min(6, { message: 'Password should contain at least 6 characters' }).max(72),
```
Comment (catalinpit) [inline apps/web/src/components/forms/signup.tsx:24]: Since it has min and max, should the message be something like "Password should contain between 6 and 72 characters"?

File: apps/web/src/components/forms/password.tsx [hunk 2]
```diff
@@ -20,9 +20,18 @@ import { FormErrorMessage } from '../form/form-error-message';
 
 export const ZPasswordFormSchema = z
   .object({
-    currentPassword: z.string().min(6).max(72),
-    password: z.string().min(6).max(72),
-    repeatedPassword: z.string().min(6).max(72),
+    currentPassword: z
+      .string()
+      .min(6, { message: 'Password should contain at least 6 characters' })
```
Comment (catalinpit) [inline apps/web/src/components/forms/password.tsx:25]: Same comment as below for all the fields that have min and max.

File: apps/web/src/components/forms/signup.tsx (hunk 1 above)
Comment (anikdhabal) [reply apps/web/src/components/forms/signup.tsx:24]: Generallly we don't set password more then 72 characters. So, I think it's fine now.
What if we can add validation messages for both the min and max cases? For max- "Password should not contain more than 72 characters".

Comment (anikdhabal) [reply apps/web/src/components/forms/signup.tsx:24]: @catalinpit what do you think?

Comment (catalinpit) [reply apps/web/src/components/forms/signup.tsx:24]: You are right. Please add the message for the max value as well.

Comment (anikdhabal) [reply apps/web/src/components/forms/signup.tsx]: Done

**Comment by anikdhabal** [comment]
@catalinpit I've updated it.

**Comment by catalinpit** [comment]
Looks good, thanks for the PR!

**Review by catalinpit — APPROVED** [review]
