### PR TITLE
fix: trimmed long file names for better UX

### LINKED ISSUE #755: [DOC-385] Long Document Names Breaking UI
### **Description**

Uploaded documents with very long file names are breaking the UI of the confirm signing dialog

#### Complete Signing Page

**Proposed Solution**

* Truncate the document name in the dialog to a specific length

### **Alternatives**

* No other alternatives

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-385](https://linear.app/documenso/issue/DOC-385/long-document-names-breaking-ui)</sub>

### PR DESCRIPTION
**Pull request by Mohith234**
Fixes #755 

### Notes for Reviewers
- The max length of the title is set to be `16`
- If the length of the title is <16 it returns the original one.
- Or else the title will be the first 8 characters (start) and last 8 characters (end)
- The truncated file name will look like `start...end`

### Screenshot for reference

image

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

File: apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx [hunk 1]
```diff
@@ -23,7 +32,7 @@ export const SignDialog = ({
   onSignatureComplete,
 }: SignDialogProps) => {
   const [showDialog, setShowDialog] = useState(false);
-
+  const truncatedTitle = truncateTitle(document.title, 16);
```
Comment (catalinpit) [inline apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:35]: Out of curiosity, what is the reason behind `16` as the max length? Is it the maximum length without breaking the UI?

File: apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx [hunk 2]
```diff
@@ -9,6 +9,15 @@ import {
   DialogTrigger,
 } from '@documenso/ui/primitives/dialog';
 
+const truncateTitle = (title: string, maxLength: number) => {
```
Comment (catalinpit) [inline apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:12]: I'm thinking we should extract this in a place like `/web/src/helpers` for example, so it can re-used if necessary.

**Review by catalinpit — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx (hunk 1 above)
Comment (Mohith234) [reply apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:35]: @catalinpit Just a random length. I saw that it was correctly fitting for the current UI. It can be modified if needed.

File: apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx (hunk 2 above)
Comment (Mohith234) [reply apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:12]: @catalinpit Sure, I'm on it !

File: apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx [hunk 3]
```diff
@@ -9,6 +9,15 @@ import {
...
+  if (title.length <= maxLength) {
+    return title;
+  }
+  const start = title.slice(0, maxLength / 2);
+  const end = title.slice(-maxLength / 2);
```
[the remark this answers is not in the document]
Comment (Mohith234) [reply apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:17]: Did you mean a line spacing after these statements?

[the remark this answers is not in the document]
Comment (catalinpit) [reply apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:17]: Yes, please!

File: apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx (hunk 1 above)
Comment (catalinpit) [reply apps/web/src/app/(signing)/sign/[token]/sign-dialog.tsx:35]: Got it!

**Comment by dephraiim** [comment]
@Mohith234 Can you do the same for the signing complete page?

**Review by catalinpit — APPROVED** [review]
thanks for the improvement!
