### PR TITLE
fix: sign up with existing account email bug

### LINKED ISSUE #511: [improvement] Signing up using existing email does not show correct message
[Description]
If a person uses documenso occasionally, they may not remember that they already have account.if they try to sign up again using same email id, correct error message is not shown.They may think that it is a problem with the system. We should have a message like "user already exists".
Screenshot from 2023-10-03 21-02-09

### PR DESCRIPTION
**Pull request by anjy7**
Fixes  #511

Screenshot from 2023-10-04 02-09-43

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by anjy7** [comment]
> Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:
> 
> https://documen.so/cla

Done

File: packages/trpc/server/auth-router/router.ts [hunk 1]
```diff
@@ -12,13 +12,18 @@ export const authRouter = router({
...
+          code: 'BAD_REQUEST',
+          message: 'User with this email already exists. Please use a different email address.',
+        });
+      } else {
+        throw new TRPCError({
+          code: 'BAD_REQUEST',
+          message:
+            'We were unable to create your account. Please review the information you provided and try again.',
+        });
+      }
```
Comment (dguyen) [inline packages/trpc/server/auth-router/router.ts:26]: I think doing something like this would be more optimal as it would allow us to add more errors in the future if need be:

```
let message = 'We were unable to create your account. Please review the information you provided and try again.';

if (err instanceof Error && err.message === 'User already exists') {
  message = 'User with this email already exists. Please use a different email address.';
}

throw new TRPCError({
  code: 'BAD_REQUEST',
  message,
});
```

Comment (anjy7) [reply packages/trpc/server/auth-router/router.ts:26]: Sure, I’ll make the changes

Comment (anjy7) [reply packages/trpc/server/auth-router/router.ts]: Made the changes, please have a look @dguyen

**Comment by dguyen** [comment]
looks good to me, thanks!

/tip 35
