### PR TITLE
fix: add a defaultValue to SignaturePad for persisting signatures

### LINKED ISSUE #520: [Bug] - Signature State Should Persist Unless Cleared or Refreshed
**Description:**

Currently, if we add our email at https://documenso.com and our signature in the box, the state does not persist upon opening the _**Add your signature**_ modal. The ideal case is to clear it upon refresh or when the user clicks the **clear signature** button

Please refer to the video below for more reference :)

[screen-capture.webm](https://github.com/documenso/documenso/assets/23498248/1a23da4e-e0d2-4539-8333-ecdc34b2d001)

### PR DESCRIPTION
**Pull request by zahid47**
closes #520

### CODE REVIEW

**Comment by Mythie** [comment]
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

**Comment by zahid47** [comment]
> Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:
> 
> https://documen.so/cla

Done!

**Review by Mythie — APPROVED** [review]

File: apps/marketing/src/components/(marketing)/widget.tsx [hunk 1]
```diff
@@ -391,6 +391,7 @@ export const Widget = ({ className, children, ...props }: WidgetProps) => {
 
           <SignaturePad
             className="aspect-video w-full rounded-md border"
+            defaultValue={draftSignatureDataUrl || ''}
```
Comment (dguyen) [inline apps/marketing/src/components/(marketing)/widget.tsx:394]: Shouldn't this be `signatureDataUrl || ''` instead?

Assuming that we should only persist signatures that they explicitly click 'confirm' on

Comment (zahid47) [reply apps/marketing/src/components/(marketing)/widget.tsx:394]: You are correct. Otherwise, there's also a mismatch between the modal and the preview. Pushing an update now.

**Comment by dguyen** [comment]
lgtm thanks @zahid47 

/tip 25

**Comment by zahid47** [comment]
> lgtm thanks @zahid47
> 
> /tip 25

image
that's so kind of you, tysm!
